name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '⚠️ Breaking changes'
    labels:
      - 'breaking'
      - 'breaking-change'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '📚 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '🏠 Internal'
    labels:
      - 'chore'
      - 'internal'
      - 'dependencies'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
      - 'breaking-change'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bug'
  default: patch

template: |
  ## What's changed

  $CHANGES

  **Full changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
